import React,{useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
type P={x:number,y:number};const T=32,HOST="https://9e16af3d-1614-4c26-82de-bb8aad908510.sandbox.floot.app",A=[HOST+"/_cdn/static/17695da1-3723-4809-8f83-44c964f5c1c4.png",HOST+"/_cdn/static/f2da5b75-31f3-485a-b6ae-7adb1b238d65.png",HOST+"/_cdn/static/7a4339d3-111b-408f-bc2c-bcb9878ffd1f.png",HOST+"/_cdn/static/80057405-dfaa-4972-a7cd-b27050192f95.png"];
function Game(){const cv=useRef<HTMLCanvasElement>(null),p=useRef<P>({x:32,y:43}),to=useRef<P>({x:32,y:43});const[msg,setMsg]=useState("Rejoins le Bureau des missions."),[panel,setPanel]=useState("");
useEffect(()=>{const c=cv.current!,g=c.getContext("2d")!,im=A.map(s=>{let i=new Image;i.crossOrigin="anonymous";i.src=s;return i});let raf=0,last=0;const resize=()=>{c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;g.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)};resize();addEventListener("resize",resize);
const tile=(img:HTMLImageElement,sx:number,sy:number,x:number,y:number,w=T,h=T)=>{if(img.complete&&img.naturalWidth)g.drawImage(img,sx*T,sy*T,T,T,x,y,w,h)};
const building=(sx:number,sy:number,sw:number,sh:number,x:number,y:number,w:number,h:number)=>{if(im[1].complete&&im[1].naturalWidth)g.drawImage(im[1],sx*T,sy*T,sw*T,sh*T,x,y,w,h)};
const draw=(n:number)=>{let dt=Math.min(32,n-last)/16.7;last=n;const sw=innerWidth,sh=innerHeight,q=p.current,d=to.current,dx=d.x-q.x,dy=d.y-q.y,dd=Math.hypot(dx,dy);if(dd>.04){let s=Math.min(dd,.105*dt);q.x+=dx/dd*s;q.y+=dy/dd*s}g.imageSmoothingEnabled=false;g.fillStyle="#183221";g.fillRect(0,0,sw,sh);let ox=Math.round(sw/2-q.x*T),oy=Math.round(sh/2-q.y*T);
for(let y=0;y<64;y++)for(let x=0;x<64;x++){let X=ox+x*T,Y=oy+y*T;if(X<-T||Y<-T||X>sw||Y>sh)continue;let road=Math.abs(x-32)<4||Math.abs(y-32)<3;if(im[0].complete&&im[0].naturalWidth)tile(im[0],road?5+(x+y)%3:(x*3+y*5)%4,road?4:0,X,Y);else{g.fillStyle=road?"#917651":"#315a39";g.fillRect(X,Y,T,T)}}
if(im[0].complete&&im[0].naturalWidth){for(let y=8;y<57;y++)tile(im[0],2+(y%3),5,ox+4*T,oy+y*T,T,T);for(let x=4;x<12;x++)tile(im[0],6,10,ox+x*T,oy+31*T,T,T)}if(im[3]?.complete&&im[3].naturalWidth){for(let y=4;y<60;y+=3){tile(im[3],(y*3)%12,2+(y%5),ox+12*T,oy+y*T,48,56);tile(im[3],(y*5)%12,8+(y%4),ox+51*T,oy+(y+1)*T,48,56)}for(let x=15;x<50;x+=5){tile(im[3],(x*3)%14,12,ox+x*T,oy+16*T,40,40);tile(im[3],(x*5)%14,13,ox+x*T,oy+49*T,40,40)}}
building(0,0,8,8,ox+27*T,oy+4*T,10*T,10*T);building(8,0,7,7,ox+17*T,oy+21*T,8*T,8*T);building(15,0,7,7,ox+40*T,oy+21*T,8*T,8*T);building(0,8,7,7,ox+18*T,oy+39*T,8*T,8*T);building(8,8,7,7,ox+39*T,oy+39*T,8*T,8*T);
g.textAlign="center";g.font="800 10px system-ui";g.fillStyle="#ffe6a0";g.fillText("TOUR DU CONSEIL",ox+32*T,oy+3*T);g.fillText("MISSIONS",ox+21*T,oy+20*T);g.fillText("MARCHÉ",ox+44*T,oy+20*T);
if(im[2].complete&&im[2].naturalWidth){let moving=dd>.08,fr=moving?Math.floor(n/140)%4:0;g.drawImage(im[2],fr*T,0,T,T,sw/2-20,sh/2-28,40,40)}else{g.fillStyle="#202a26";g.fillRect(sw/2-9,sh/2-18,18,28)}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize)}},[]);
const tap=(e:React.PointerEvent)=>{if(panel)return;to.current={x:p.current.x+(e.clientX-innerWidth/2)/T,y:p.current.y+(e.clientY-innerHeight/2)/T};setMsg("Déplacement…")};
return <main><canvas ref={cv} onPointerDown={tap}/><header><b>ASPIRANT III</b><span>PV 100/100 · ÉNERGIE 100/100</span><span>150 Ryō · EXP 0 · RANG 0</span></header><div className="msg">{msg}</div><section><b>MISSION PRINCIPALE</b><br/>Va au Bureau des missions.</section><nav><button onClick={()=>setPanel("profil")}>🥷</button><button onClick={()=>setPanel("sac")}>🎒</button></nav>{panel&&<div className="modal"><h2>{panel==="profil"?"Fiche Ninja":"Inventaire"}</h2>{panel==="profil"?<p>PV 100/100<br/>Énergie 100/100<br/>Force 12<br/>Défense 10<br/>Technique 14<br/><br/>Rang : Aspirant III</p>:<p>◆ Potion de soin<br/>◆ Kunai ×3</p>}<button onClick={()=>setPanel("")}>Fermer</button></div>}</main>}createRoot(document.getElementById("app")!).render(<Game/>);